import type { Client, LogEntry, Rule, Vendor, VerificationRequest } from './types'

export const vendors: Vendor[] = [
  {
    id: 'gbg',
    name: 'GBG',
    logo: 'https://dummyimage.com/120x40/111827/fff&text=GBG',
    status: 'online',
    supportedChecks: ['Document', 'Watchlist', 'Liveness'],
    region: 'Global',
    avgLatency: 3.2,
    apiKey: 'gbg_sandbox_key',
    secret: 'gbg_secret',
    sandbox: true,
    documentScan: true,
    liveness: true,
    watchlist: true,
    faceMatch: true,
    priority: 1,
    routingTag: 'primary-docs',
  },
  {
    id: 'veriff',
    name: 'Veriff',
    logo: 'https://dummyimage.com/120x40/1d4ed8/fff&text=Veriff',
    status: 'degraded',
    supportedChecks: ['Document', 'Face'],
    region: 'EU',
    avgLatency: 4.8,
    apiKey: 'veriff_key',
    secret: 'veriff_secret',
    sandbox: false,
    documentScan: true,
    liveness: false,
    watchlist: true,
    faceMatch: true,
    priority: 2,
    routingTag: 'eu-priority',
  },
  {
    id: 'facephi',
    name: 'Facephi',
    logo: 'https://dummyimage.com/120x40/0f172a/fff&text=Facephi',
    status: 'online',
    supportedChecks: ['Liveness', 'Face'],
    region: 'LATAM',
    avgLatency: 2.6,
    apiKey: 'facephi_key',
    secret: 'facephi_secret',
    sandbox: true,
    documentScan: false,
    liveness: true,
    watchlist: false,
    faceMatch: true,
    priority: 3,
    routingTag: 'latam-liveness',
  },
]

export const clients: Client[] = [
  {
    id: 'neo',
    name: 'Neo Bank',
    apiKey: 'neo_live_123',
    allowedVendors: ['GBG', 'Veriff'],
    flow: 'Primary',
    riskProfile: 'Medium',
    status: 'Active',
    thresholds: { score: 0.75, manualReview: 0.55 },
    webhooks: ['https://neo-bank.app/webhook/kyc'],
    onboardingConfig: {
      fields: {
        fullName: true,
        email: true,
        phone: true,
        gender: true,
        country: true,
        address: false,
        nationalId: true,
      },
      documents: {
        front: true,
        back: true,
        selfie: true,
      },
    },
  },
  {
    id: 'crypto',
    name: 'CryptoX',
    apiKey: 'crypto_sandbox',
    allowedVendors: ['Facephi'],
    flow: 'Parallel',
    riskProfile: 'High',
    status: 'Active',
    thresholds: { score: 0.8, manualReview: 0.6 },
    webhooks: ['https://crypto-x.dev/webhooks/kyc'],
    onboardingConfig: {
      fields: {
        fullName: true,
        email: true,
        phone: true,
        gender: false,
        country: true,
        address: true,
        nationalId: true,
      },
      documents: {
        front: true,
        back: false,
        selfie: true,
      },
    },
  },
  {
    id: 'telco',
    name: 'SkyTel',
    apiKey: 'skytel_live',
    allowedVendors: ['GBG', 'Facephi'],
    flow: 'Fallback',
    riskProfile: 'Low',
    status: 'Paused',
    thresholds: { score: 0.7, manualReview: 0.5 },
    webhooks: ['https://skytel.com/api/kyc'],
    onboardingConfig: {
      fields: {
        fullName: true,
        email: true,
        phone: false,
        gender: false,
        country: true,
        address: true,
        nationalId: false,
      },
      documents: {
        front: true,
        back: true,
        selfie: false,
      },
    },
  },
]

export const recentVerifications: VerificationRequest[] = [
  {
    id: '#REQ-1032',
    client: 'Neo Bank',
    vendor: 'GBG',
    document: 'Passport',
    country: 'AU',
    score: 0.82,
    status: 'success',
    timestamp: '2025-11-26T08:30:00Z',
  },
  {
    id: '#REQ-1033',
    client: 'CryptoX',
    vendor: 'Veriff',
    document: 'Driver License',
    country: 'SG',
    score: 0.44,
    status: 'failed',
    timestamp: '2025-11-26T08:27:00Z',
  },
  {
    id: '#REQ-1034',
    client: 'Neo Bank',
    vendor: 'GBG',
    document: 'National ID',
    country: 'NZ',
    score: 0.66,
    status: 'review',
    timestamp: '2025-11-26T08:15:00Z',
  },
  {
    id: '#REQ-1035',
    client: 'SkyTel',
    vendor: 'Facephi',
    document: 'Passport',
    country: 'BR',
    score: 0.91,
    status: 'success',
    timestamp: '2025-11-26T08:10:00Z',
  },
]

export const logs: LogEntry[] = [
  {
    id: 'log-1',
    timestamp: '2025-11-26T08:10:00Z',
    vendor: 'GBG',
    type: 'API',
    requestId: '#REQ-1032',
    payload: { latency: '3.2s', decision: 'Approved' },
  },
  {
    id: 'log-2',
    timestamp: '2025-11-26T08:05:00Z',
    vendor: 'Veriff',
    type: 'Error',
    requestId: '#REQ-1033',
    payload: { code: 'DOC_BLUR', message: 'Document too blurry' },
  },
  {
    id: 'log-3',
    timestamp: '2025-11-26T07:58:00Z',
    vendor: 'Orchestrator',
    type: 'Orchestrator',
    requestId: '#REQ-1034',
    payload: { routing: 'Fallback -> GBG' },
  },
]

export const rules: Rule[] = [
  {
    id: 'rule-1',
    name: 'High risk countries',
    priority: 1,
    enabled: true,
    conditions: ['country IN (NG, IR, KP)'],
    action: 'Route to manual review',
  },
  {
    id: 'rule-2',
    name: 'Watchlist exact match',
    priority: 2,
    enabled: true,
    conditions: ['watchlist_match == true'],
    action: 'Auto reject',
  },
  {
    id: 'rule-3',
    name: 'Low risk fast track',
    priority: 3,
    enabled: false,
    conditions: ['risk_score > 0.85', 'document_type == Passport'],
    action: 'Auto approve',
  },
]

export const dailySeries = [
  { day: 'Mon', total: 180, success: 160 },
  { day: 'Tue', total: 210, success: 190 },
  { day: 'Wed', total: 240, success: 220 },
  { day: 'Thu', total: 200, success: 180 },
  { day: 'Fri', total: 260, success: 240 },
  { day: 'Sat', total: 190, success: 170 },
  { day: 'Sun', total: 170, success: 150 },
]

export const vendorLatencySeries = [
  { vendor: 'GBG', latency: 3.2 },
  { vendor: 'Veriff', latency: 4.8 },
  { vendor: 'Facephi', latency: 2.6 },
  { vendor: 'Onfido', latency: 3.9 },
]

export const failureBreakdown = [
  { reason: 'Blurry document', value: 32 },
  { reason: 'Watchlist hit', value: 16 },
  { reason: 'Face mismatch', value: 22 },
  { reason: 'Expired ID', value: 12 },
  { reason: 'Other', value: 18 },
]

